name: sc-genomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - scanpy
  - anndata
  - pip
  - pip:
    - umi-tools
