name: lab3-analysis
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - scanpy
  - anndata

